# Generated by Django 4.2.6 on 2024-09-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("url", models.URLField(max_length=255, unique=True)),
                ("background_image", models.ImageField(upload_to="bg_images/")),
            ],
        ),
        migrations.CreateModel(
            name="WebsiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("licence_key", models.CharField(max_length=250, unique=True)),
                ("chatbot_image", models.ImageField(upload_to="chatbot_images/")),
                ("heading_text", models.CharField(max_length=500)),
                ("welcome_message", models.TextField()),
                (
                    "send_message_icon",
                    models.ImageField(upload_to="send_message_icons/"),
                ),
                ("color_scheme", models.CharField(max_length=7)),
                (
                    "website",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_app.website",
                    ),
                ),
            ],
        ),
    ]
