# Generated by Django 4.2.6 on 2024-09-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('background_image', models.ImageField(upload_to='bg_images/')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_key', models.CharField(blank=True, max_length=250, null=True)),
                ('chat_bot_image', models.ImageField(upload_to='chatbot_images/')),
                ('heading_text', models.CharField(blank=True, max_length=500, null=True)),
                ('welcome_message', models.TextField(blank=True, max_length=700, null=True)),
                ('send_message_icon', models.ImageField(upload_to='send_message_icons/')),
                ('color_scheme', models.CharField(blank=True, max_length=7, null=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.website')),
            ],
        ),
    ]
