# Generated by Django 4.2.6 on 2024-09-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteconfiguration',
            name='licence_key',
        ),
    ]
