# Generated by Django 3.2.25 on 2024-09-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteconfiguration',
            name='color_scheme',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='websiteconfiguration',
            name='heading_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='websiteconfiguration',
            name='licence_key',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='websiteconfiguration',
            name='welcome_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
